// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePipelinesPool) DeepCopyInto(out *AzurePipelinesPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePipelinesPool.
func (in *AzurePipelinesPool) DeepCopy() *AzurePipelinesPool {
	if in == nil {
		return nil
	}
	out := new(AzurePipelinesPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzurePipelinesPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePipelinesPoolList) DeepCopyInto(out *AzurePipelinesPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AzurePipelinesPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePipelinesPoolList.
func (in *AzurePipelinesPoolList) DeepCopy() *AzurePipelinesPoolList {
	if in == nil {
		return nil
	}
	out := new(AzurePipelinesPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AzurePipelinesPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePipelinesPoolSpec) DeepCopyInto(out *AzurePipelinesPoolSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePipelinesPoolSpec.
func (in *AzurePipelinesPoolSpec) DeepCopy() *AzurePipelinesPoolSpec {
	if in == nil {
		return nil
	}
	out := new(AzurePipelinesPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AzurePipelinesPoolStatus) DeepCopyInto(out *AzurePipelinesPoolStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AzurePipelinesPoolStatus.
func (in *AzurePipelinesPoolStatus) DeepCopy() *AzurePipelinesPoolStatus {
	if in == nil {
		return nil
	}
	out := new(AzurePipelinesPoolStatus)
	in.DeepCopyInto(out)
	return out
}
