apiVersion: dev.azure.com/v1alpha1
kind: AzurePipelinesPool
metadata:
  name: azurepipelinespool-operator
  namespace: azuredevops
spec:
  controllerImage: prebansa/k8s-poolprovider:v2.22
  buildkitReplicas: 1
  agentPools:
  - name: windows
    spec:
      containers:
      - name: vsts-agent
        image: prebansa/myagent:v5.17
  - name: linux
    spec:
      containers:
      - name: vsts-agent
        image: prebansa/myagent:v6.2